export const FETCHING_POST_REQUEST = 'FETCHING_POST_REQUEST'
export const FETCHING_POST_SUCCESS = 'FETCHING_POST_SUCCESS'
export const FETCHING_POST_FAILURE = 'FETCHING_POST_FAILURE'

export const FETCHING_DETAILS_REQUEST = 'FETCHING_DETAILS_REQUEST'
export const FETCHING_DETAILS_SUCCESS = 'FETCHING_DETAILS_SUCCESS'
export const FETCHING_DETAILS_FAILURE = 'FETCHING_DETAILS_FAILURE'

export const SESSION_RESTORING = 'SESSION_RESTORING'
export const SESSION_LOADING = 'SESSION_LOADING'
export const SESSION_SUCCESS = 'SESSION_SUCCESS'
export const SESSION_ERROR = 'SESSION_ERROR'
export const SESSION_LOGOUT = 'SESSION_LOGOUT'  