export const FETCHING_POST_REQUEST = 'FETCHING_POST_REQUEST'
export const FETCHING_POST_SUCCESS = 'FETCHING_POST_SUCCESS'
export const FETCHING_POST_FAILURE = 'FETCHING_POST_FAILURE'

export const FETCHING_DETAILS_REQUEST = 'FETCHING_DETAILS_REQUEST'
export const FETCHING_DETAILS_SUCCESS = 'FETCHING_DETAILS_SUCCESS'
export const FETCHING_DETAILS_FAILURE = 'FETCHING_DETAILS_FAILURE'